
COND_FIELD_NAME = "cond_result"
OPTION_TYPE_BUY = "buy"
OPTION_TYPE_SELL = "sell"
OPTION_TYPE_END_SELL = "end_sell"
DEFAULT_START_DATE = "19900101"
# DEFAULT_START_DATE = "20221101"
BUY_TIP = "buy"
SELL_TIP = "sell"
