
COND_FIELD_NAME = "cond_result"
OPTION_TYPE_BUY = "buy"
OPTION_TYPE_SELL = "sell"
OPTION_TYPE_NONE = "none"
OPTION_TYPE_END_SELL = "end_sell"
# DEFAULT_START_DATE = "19900101"
DEFAULT_START_DATE = "20070101"
DEFAULT_START_DATE_TEST = "20220701"
# DEFAULT_START_DATE = "20221101"
DEFAULT_START_DATE_COIN = "2007-01-01 00:00:00"

RUN_MODEL_STOCK_A_TIP = "stock_a"
RUN_MODEL_BINANCE_TIP = "binance"
RUN_MODEL_MEXC_TIP = "mexc"

# prepare、submit、success、fail
STATUS_SUCCESS_TIP = "success"
STATUS_FAIL_TIP = "fail"
STATUS_PREPARE_TIP = "prepare"
STATUS_SUBMIT_TIP = "submit"

OPTION_AMOUNT_AUTO_TIP = "auto"
OPTION_AMOUNT_FIX_TIP = "fix"
OPTION_MAX_BUY_COUNT = 2


OPTION_AMOUNT_TYPE_AUTO_TIP = "auto"
ALL_DEGREE_NUM = 10001
MIN_PRICE_AMOUNT = 2.5

DEFAULT_COIN_START_DATE = "2017-01-01 00:00:00"
DEFAULT_COIN_START_DATE_M = "2023-07-01 00:00:00"
DEFAULT_COIN_MAX_ROW_LIMIT = 1000

# 交易手续费，含印花税、证券商费
TRADE_FEE = 0.003
TRADE_FEE_MEXC_FEE = 0.001
# 持仓成本费，减扣掉年化利润12，考虑时间成本， - (0.120/365) * 天数
PER_DAY_KEEP_FEE = 0.0003288
ANALYSE_DAY_CNT = 50

# test|prod
# RUN_TYPE = "test"
RUN_TYPE = "prod"

# MEXC_RUN_TYPE = "test"
MEXC_RUN_TYPE = "prod"

# 请求kline时的最大超时时长
MEXC_REQUEST_TIMEOUT = 30
MEXC_OPTION_MAX_BUY_COUNT = 5
# 买入和卖出时，因为有时间差，可以在分析的价格上加价买入和减价卖出，以便尽可能及时按策略执行
MEXC_BUY_PRICE_FLOAT = 0.001
MEXC_SELL_PRICE_FLOAT = 0.002
